### ISSUE TITLE
CT-fire V2.0 installation issue in macOS Catalina and I am using MATLAB 2020a

### ISSUE THREAD

**Issue by MEKH1** [uw-loci/curvelets#13]
I am using macOS Catalina trying to install CT-fire using it with MATLAB 2020a, but I am facing an installation error, is it because I am using the 2020a version, or is it from macOS Catalina, if there is a solution for my issue please contact me.

**Comment by ctrueden** [comment]
@MEKH1 What is the installation error? Could you please copy/paste it, and/or share a screenshot?

**Comment by MEKH1** [comment]
it's not an error but when I follow the instruction for installing it, does not work for me, does this standalone package works on the specification mentioned above?

**Comment by ctrueden** [comment]
@yuminguw Do you know whether CT-FIRE works with MATLAB 2020a, and/or with macOS Catalina?

**Comment by MEKH1** [comment]
Actually, this is my question

**Comment by yuminguw** [comment]
The code worked fine on macOS Catalina versions(10.15.4, 10.15.6) we tested.
 The source code version of CT-FIRE and CurveAlign should work on any Matlab versions later than 2014b including 2020a. However, the standalone version needs a specific version of Matlab MCR installation. Specifically, CT-FIRE 2.0/CurveAlign 4.0  standalone needs a Matlab MCR 2014b, while CT-FIRE 3.0/CurveAlign 5.0 standalone needs MCR 2018b. More details about the standalone versions can be seen here: https://github.com/uw-loci/curvelets/releases/

**Comment by MEKH1** [comment]
Thanks a lot, everything went well, I have another small question when I type ctFIRE in the command window I have this message "Please make sure you have downloaded the Curvelets library from http://curvelet.org" then I have one window of CT-Fire poped up, is that right, because when I was reading the manual, it said there will be 3 windows?

**Comment by yuminguw** [comment]
@MEKH1 We don't have permission to distribute curvelets library so the users have to go to the   http://curvelet.org to download it by themselves if they would like to try the source code version.  We generally recommend standalone versions for most users.  For the source code version, the users need to make sure that all the required libraries/toolboxes are available and are added to the Matlab path.

**Comment by yuminguw** [comment]
More details about the installation and usage of CT-FIRE can be seen on wiki page at https://github.com/uw-loci/curvelets/wiki
or on our lab website at: https://eliceirilab.org/software/ctfire/.
