### ISSUE TITLE
CT-Fire analysis output table cannot be copied

### ISSUE THREAD

**Issue by ranran-02** [uw-loci/curvelets#27]
Hello! Thank you for the standalone APP as it enables automated analysis for different parameters of collagen. ^_^
However, I would like to ask how can I copy the output table? 

CTRL + C does not always work and I cannot also do a right-click to select "copy". 

I tried running the CurveAlign and the analysis output table enables me to save it in a CSV file. More so, when I run the CT-Fire module using the Curve Align, I encounter the same problem with the standalone APP of the CT-Fire as mentioned above. 

I would be grateful if you could help me figure out how to copy from the CT-FIRE output analysis table to avoid any human error for downstream analysis. Thank you so much. 

I am currently using the following versions: 
* CT-FIRE 3.0 MATLAB 2018b windows standalone 20240607build
* CurveAlign 5.0 MATLAB 2018b windows standalone 20240607build

**Comment by yuminguw** [comment]
Hi ranran-02, 

Thanks for your inquire and detailed description about the issue. 
Yes, the current output table from the main CT-FIRE can not be saved as you described.
To combine the summary statistics including mean and others (such as median, variance, etc) of the fiber properties,  I would suggest you use the "Advanced output control" module whose use is described in the Tutorial 3 of the[ CT-FIRE quick manual](https://github.com/uw-loci/curvelets/releases/download/5.0/CA5.0andCTF3.0_manual_testImages.zip).  
The combined summary statistics of each fiber property  will be saved into a spreadsheet of an excel file as shown below:
![image](https://github.com/user-attachments/assets/c1bef2fc-3349-465f-8f69-15062d6aca8e)

In addition, you can copy and paste the output table in the the "Advanced output control" module to an excel file as needed. 
![image](https://github.com/user-attachments/assets/834cfaa9-e9a7-44b9-b5bb-8fea47c1b9c8)

Please try it out and let us know how it goes.

Best,
Yuming

**Comment by yuminguw** [comment]
@ranran-02 Thanks for the update and additional information. Glad to clear.
